// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: deep-blue; icon-glyph: hard-hat;
const DATA_URL='https://xiadasy.github.io/site-labor-assistant/widget-summary.json';
const SITE_URL='https://xiadasy.github.io/site-labor-assistant/';
const money=n=>`¥${Number(n||0).toLocaleString('zh-CN')}`;
const add=(s,v,z,c,b=false)=>{const t=s.addText(String(v));t.font=b?Font.boldSystemFont(z):Font.systemFont(z);t.textColor=new Color(c);t.lineLimit=1;t.minimumScaleFactor=.65;return t};
async function load(){const fm=FileManager.local(),p=fm.joinPath(fm.documentsDirectory(),'dongfang-labor-summary.json');try{const r=new Request(DATA_URL);r.timeoutInterval=8;const d=await r.loadJSON();fm.writeString(p,JSON.stringify(d));return d}catch(e){if(fm.fileExists(p))return JSON.parse(fm.readString(p));throw e}}
const data=await load(),parts=String(args.widgetParameter||'all|2026-06').split('|'),uid=parts[0]||'all',month=parts[1]||'2026-06',units=uid==='all'?data.units:data.units.filter(u=>u.id===uid),family=config.widgetFamily||'medium',sum=k=>units.reduce((s,u)=>s+Number(u[k]||0),0),pay=u=>u.payrollHistory.find(x=>x.month===month),expected=units.reduce((s,u)=>s+Number(pay(u)?.expectedTotal||0),0),paid=units.reduce((s,u)=>s+Number(pay(u)?.paidTotal||0),0),monthLabel=`${Number(month.slice(5))}月`;
const w=new ListWidget();w.url=SITE_URL;w.backgroundColor=Color.dynamic(new Color('F4F6F3'),new Color('171A19'));w.setPadding(14,15,13,15);const h=w.addStack();add(h,family==='small'?'东方枢纽':data.project,12,'59605D',true);h.addSpacer();add(h,`${uid==='all'?'全部':units[0]?.name||'全部'} · ${monthLabel}`,9,'7A817E');
if(family==='small'){w.addSpacer(12);add(w,sum('active'),35,'18211E',true);add(w,`在场 · 建档 ${sum('records')}`,10,'6B726F');w.addSpacer(9);add(w,money(paid),18,'267A6A',true);add(w,`实发 · 应发${money(expected)}`,9,'6B726F');w.addSpacer();add(w,`重点 ${data.focusOver55}人 · 证书 ${sum('certificateCount')}本`,9,'858B88')}else{w.addSpacer(9);const s=w.addStack(),l=s.addStack(),r=(s.addSpacer(),s.addStack());l.layoutVertically();r.layoutVertically();add(l,sum('active'),28,'18211E',true);add(l,`当前在场 / 建档 ${sum('records')}`,10,'6B726F');add(r,money(paid),22,'267A6A',true);add(r,`${monthLabel}实发 / 应发${money(expected)}`,10,'6B726F');w.addSpacer(9);const line=w.addStack();line.size=new Size(0,1);line.backgroundColor=new Color('D8DDDA');w.addSpacer(8);for(const u of units){const row=w.addStack();const bar=row.addStack();bar.size=new Size(5,21);bar.cornerRadius=2;bar.backgroundColor=new Color(u.id==='gongqiang'?'E77728':'267A6A');row.addSpacer(7);add(row,u.name,12,'262C29',true);row.addSpacer(7);add(row,`${u.active}人在场`,10,'737A77');row.addSpacer();add(row,pay(u)?money(pay(u).paidTotal):'暂无',11,'267A6A',true);w.addSpacer(6)}if(family==='large'){w.addSpacer(7);const t=w.addStack();add(t,'管理提醒',11,'59605D',true);t.addSpacer();add(t,`超55岁 ${data.focusOver55}人`,10,'B84738',true);w.addSpacer(7);add(w,`持证 ${data.certifiedPeople}人 · 证书 ${data.certificateCount}本`,11,'267A6A',true);w.addSpacer(6);add(w,'点按进入加密人员档案查询',10,'858B88')}w.addSpacer();const f=w.addStack();add(f,`花名册 ${data.rosterVersion}`,9,'858B88');f.addSpacer();add(f,'查询 ›',9,'267A6A',true)}
w.refreshAfterDate=new Date(Date.now()+30*60000);Script.setWidget(w);Script.complete();
