// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: deep-blue; icon-glyph: hard-hat;
/** 东方枢纽劳务挂件 V2.0 - 稳定版 */
const DATA_URL = 'https://dongfang-labor-admin.a15221082942.workers.dev/api/summary';
const SITE_URL = 'https://xiadasy.github.io/site-labor-assistant/';
const FALLBACK = {version:1,project:'东方枢纽工程',updatedAt:'2026-07-10 23:15',rosterVersion:'2026-07-08',records:49,active:37,focusOver55:3,certificateCount:48,certifiedPeople:29,units:[{id:'gongqiang',name:'共强',records:23,active:18,certificateCount:20,payrollHistory:[{month:'2026-06',expectedTotal:246830,paidTotal:0,peopleCount:19,status:'待发放'},{month:'2026-05',expectedTotal:131960,paidTotal:122060,peopleCount:16,status:'部分成功'},{month:'2026-04',expectedTotal:32700,paidTotal:32700,peopleCount:5,status:'已发放'}]},{id:'mingfu',name:'铭富',records:26,active:19,certificateCount:28,payrollHistory:[{month:'2026-06',expectedTotal:241330,paidTotal:0,peopleCount:19,status:'待发放'},{month:'2026-05',expectedTotal:153570,paidTotal:153570,peopleCount:19,status:'已发放'},{month:'2026-04',expectedTotal:90240,paidTotal:90240,peopleCount:13,status:'已发放'},{month:'2026-03',expectedTotal:32580,paidTotal:32580,peopleCount:7,status:'已发放'}]}]};
function money(n){return '¥'+Number(n||0).toLocaleString('zh-CN')}
function text(stack,value,size,color,bold){const t=stack.addText(String(value));t.font=bold?Font.boldSystemFont(size):Font.systemFont(size);t.textColor=new Color(color);t.lineLimit=1;t.minimumScaleFactor=0.6;return t}
function payroll(unit,month){const list=unit.payrollHistory||[];for(let i=0;i<list.length;i++){if(list[i].month===month)return list[i]}return null}
async function getData(){const fm=FileManager.local();const path=fm.joinPath(fm.documentsDirectory(),'dongfang-labor-summary-v2.json');try{const req=new Request(DATA_URL+'?t='+Date.now());req.timeoutInterval=10;const value=await req.loadJSON();fm.writeString(path,JSON.stringify(value));return value}catch(error){if(fm.fileExists(path)){try{return JSON.parse(fm.readString(path))}catch(e){}}return FALLBACK}}
function makeError(error){const w=new ListWidget();w.backgroundColor=new Color('F4F6F3');w.setPadding(14,14,14,14);text(w,'东方枢纽劳务挂件',13,'59605D',true);w.addSpacer(12);text(w,'数据加载失败',18,'B84738',true);w.addSpacer(6);text(w,String(error),10,'6B726F',false);w.addSpacer();text(w,'请联网后重新运行',10,'267A6A',true);return w}
async function makeWidget(data,family,parameter){const parts=String(parameter||'all|2026-06').split('|');const unitId=parts[0]||'all';const month=parts[1]||'2026-06';const monthName=Number(month.slice(5))+'月';let units=unitId==='all'?data.units:data.units.filter(function(u){return u.id===unitId});if(!units.length)units=data.units;let records=0,active=0,certificates=0,expected=0,paid=0,paidPeople=0;for(let i=0;i<units.length;i++){const u=units[i],p=payroll(u,month);records+=Number(u.records||0);active+=Number(u.active||0);certificates+=Number(u.certificateCount||0);if(p){expected+=Number(p.expectedTotal||0);paid+=Number(p.paidTotal||0);paidPeople+=Number(p.peopleCount||0)}}
 const w=new ListWidget();w.url=SITE_URL;w.backgroundColor=Color.dynamic(new Color('F4F6F3'),new Color('171A19'));w.setPadding(14,15,13,15);const head=w.addStack();text(head,family==='small'?'东方枢纽':data.project,12,'59605D',true);head.addSpacer();text(head,(unitId==='all'?'全部':units[0].name)+' · '+monthName,9,'7A817E',false);
 if(family==='small'){w.addSpacer(12);text(w,active,34,'18211E',true);text(w,'在场 · 建档 '+records,10,'6B726F',false);w.addSpacer(8);text(w,money(paid),18,'267A6A',true);text(w,'实发 · 应发'+money(expected),9,'6B726F',false);w.addSpacer();text(w,'重点 '+data.focusOver55+'人 · 证书 '+certificates+'本',9,'B84738',true)}else{w.addSpacer(9);const summary=w.addStack();const left=summary.addStack();left.layoutVertically();text(left,active,28,'18211E',true);text(left,'当前在场 / 建档 '+records,10,'6B726F',false);summary.addSpacer();const right=summary.addStack();right.layoutVertically();text(right,money(paid),22,'267A6A',true);text(right,monthName+'实发 / 应发'+money(expected),9,'6B726F',false);w.addSpacer(9);const line=w.addStack();line.size=new Size(0,1);line.backgroundColor=new Color('D8DDDA');w.addSpacer(8);for(let j=0;j<units.length;j++){const u=units[j],p=payroll(u,month),row=w.addStack(),bar=row.addStack();bar.size=new Size(5,21);bar.cornerRadius=2;bar.backgroundColor=new Color(u.id==='gongqiang'?'E77728':'267A6A');row.addSpacer(7);text(row,u.name,12,'262C29',true);row.addSpacer(7);text(row,u.active+'人在场',10,'737A77',false);row.addSpacer();text(row,p?money(p.paidTotal):'暂无',11,p?'267A6A':'858B88',true);w.addSpacer(6)}if(family==='large'){w.addSpacer(7);const remind=w.addStack();text(remind,'管理提醒',11,'59605D',true);remind.addSpacer();text(remind,'超55岁 '+data.focusOver55+'人',10,'B84738',true);w.addSpacer(7);text(w,'发薪 '+paidPeople+'人 · 持证 '+data.certifiedPeople+'人 · 证书 '+data.certificateCount+'本',11,'267A6A',true);w.addSpacer(6);text(w,'点按进入加密人员档案查询',10,'858B88',false)}w.addSpacer();const foot=w.addStack();text(foot,'花名册 '+data.rosterVersion,9,'858B88',false);foot.addSpacer();text(foot,'查询 ›',9,'267A6A',true)}w.refreshAfterDate=new Date(Date.now()+30*60000);return w}
try{const data=await getData();const family=config.widgetFamily||'medium';const widget=await makeWidget(data,family,args.widgetParameter);if(config.runsInWidget){Script.setWidget(widget)}else{if(family==='small')await widget.presentSmall();else if(family==='large')await widget.presentLarge();else await widget.presentMedium()}}catch(error){const widget=makeError(error);if(config.runsInWidget)Script.setWidget(widget);else await widget.presentMedium()}Script.complete();
